const express = require('express');
const cors = require('cors');
const app = express();

app.use(express.json());
app.use(cors());

const port = process.env.PORT || 5000;

app.get('/', (req, res) => {
    res.send(
        [
            {   
                serial: 01,
                name: "Arcee",
                img: "" ,
                price:  "$ 87",
                quantity:  45,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 4 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "FEMALE" || "N/A" ,
            },
            {   
                serial: 02,
                name: "Arcee",
                img: "" ,
                price:  "$ 84",
                quantity:  345,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 4 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "FEMALE" || "N/A" ,
            },
            {   
                serial: 03,
                name: "Arcee",
                img: "" ,
                price:  "$ 89",
                quantity:  34,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating:  4,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "FEMALE" || "N/A" ,
            },
            {   
                serial: 04,
                name: "Blackarachnia",
                img: "" ,
                price:  "$ 54",
                quantity:  34,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating:  4.2,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "FEMALE" || "N/A" ,
            },
            {   
                serial: 05,
                name: "Blackarachnia",
                img: "" ,
                price:  "$ 23",
                quantity:  43,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating:  4.2,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "FEMALE" || "N/A" ,
            },
            {   
                serial: 06,
                name: "Blackarachnia",
                img: "" ,
                price:  "$ 34",
                quantity:  42,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating:  4.2,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "FEMALE" || "N/A" ,
            },
            {   
                serial: 07,
                name: "Bumblebee",
                img: "" ,
                price:  "$ 34",
                quantity:  34,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 4.4 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 08,
                name: "Bumblebee",
                img: "" ,
                price:  "$ 43",
                quantity:  122,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating:  4.4,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 09,
                name: "Bumblebee",
                img: "" ,
                price:  "$ 43",
                quantity:  56,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating:  4.4,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 10,
                name: "Cliffjumper",
                img: "" ,
                price:  "$ 67",
                quantity:  45,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3.2 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 11,
                name: "Cliffjumper",
                img: "" ,
                price:  "$ 67",
                quantity: 567 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating:  3.2,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 12,
                name: "Cliffjumper",
                img: "" ,
                price:  "$ 67",
                quantity:  112,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating:  3.2,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 13,
                name: "Cyclonous",
                img: "" ,
                price:  "$ 54",
                quantity:  32,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 4.2 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 14,
                name: "Cyclonous",
                img: "" ,
                price:  "$ 45",
                quantity:  34,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating:  4.2,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 15,
                name: "Cyclonous",
                img: "" ,
                price:  "$ 61",
                quantity:  32,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating:  4.2,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 16,
                name: "Grimlock",
                img: "" ,
                price:  "$ 48",
                quantity:  37,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3.8 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 17,
                name: "Grimlock",
                img: "" ,
                price:  "$ 45",
                quantity: 67 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating:  3.8,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 18,
                name: "Grimlock",
                img: "" ,
                price:  "$ 52",
                quantity:  99,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3.8 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 19,
                name: "Chromia",
                img: "" ,
                price:  "$ 76",
                quantity:  34,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating:  4,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "FEMALE" || "N/A" ,
            },
            {   
                serial: 20,
                name: "Chromia",
                img: "" ,
                price:  "$ 26",
                quantity:  85,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating:  4,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "FEMALE" || "N/A" ,
            },
            {   
                serial: 21,
                name: "Chromia",
                img: "" ,
                price:  "$ 75",
                quantity:  72,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 4 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "FEMALE" || "N/A" ,
            },
            {   
                serial: 22,
                name: "Greenlight",
                img: "" ,
                price:  "$ 67",
                quantity:  61,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "FEMALE" || "N/A" ,
            },
            {   
                serial: 23,
                name: "Chromia",
                img: "" ,
                price:  "$ 95",
                quantity: 36 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "FEMALE" || "N/A" ,
            },
            {   
                serial: 24,
                name: "Chromia",
                img: "" ,
                price:  "$ 83",
                quantity:  45,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "FEMALE" || "N/A" ,
            },
            {   
                serial: 25,
                name: "HotRod",
                img: "" ,
                price:  "$ 48",
                quantity:  83,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating:  4.1,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 26,
                name: "HotRod",
                img: "" ,
                price:  "$ 29",
                quantity:  423,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 4.1 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 27,
                name: "HotRod",
                img: "" ,
                price:  "$ 27",
                quantity:  45,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 4.1 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 28,
                name: "Ironhide",
                img: "" ,
                price:  "$ 34",
                quantity:  67,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 4.3 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 29,
                name: "Ironhide",
                img: "" ,
                price:  "$ 26",
                quantity: 23 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 4.3 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 30,
                name: "Ironhide",
                img: "" ,
                price:  "$ 85",
                quantity: 132 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 4.3 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 31,
                name: "Jazz",
                img: "" ,
                price:  "$ 78",
                quantity: 43 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3.9 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "Male" || "N/A" ,
            },
            {   
                serial: 32,
                name: "Jazz",
                img: "" ,
                price:  "$ 63",
                quantity: 40 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3.9 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 33,
                name: "Jazz",
                img: "" ,
                price:  "$ 32",
                quantity:  98,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3.9 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 34,
                name: "Jetfire",
                img: "" ,
                price:  "$ 77",
                quantity: 234 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 4.5 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 35,
                name: "Jetfire",
                img: "" ,
                price:  "$ 43",
                quantity: 77 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 4.5 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 36,
                name: "Jetfire",
                img: "" ,
                price:  "$ 88",
                quantity: 33 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 4.5 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 37,
                name: "Lancer",
                img: "" ,
                price:  "$ 44",
                quantity:  12,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3.3 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "FEMALE" || "N/A" ,
            },
            {   
                serial: 38,
                name: "Lancer",
                img: "" ,
                price:  "$ 74",
                quantity: 33 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3.3 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "FEMELE" || "N/A" ,
            },
            {   
                serial: 39,
                name: "Lancer",
                img: "" ,
                price:  "$ 32",
                quantity: 44 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3.3 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "FEMALE" || "N/A" ,
            },
            {   
                serial: 40,
                name: "Megatron",
                img: "" ,
                price:  "$ 92",
                quantity: 35 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 4.3 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 41,
                name: "Megatron",
                img: "" ,
                price:  "$ 45",
                quantity: 64 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 4.3 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 42,
                name: "Megatron",
                img: "" ,
                price:  "$ 36",
                quantity: 46 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 4.3 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 43,
                name: "Mirage",
                img: "" ,
                price:  "$ 22",
                quantity: 32 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3.7 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 44,
                name: "Mirage",
                img: "" ,
                price:  "$ 22",
                quantity: 43 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3.7 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 45,
                name: "Mirage",
                img: "" ,
                price:  "$ 25",
                quantity: 64 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3.7 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 46,
                name: "Moonracer",
                img: "" ,
                price:  "$ 89",
                quantity: 74 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3.8 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "FEMALE" || "N/A" ,   
            },
            {   
                serial: 47,
                name: "Moonracer",
                img: "" ,
                price:  "$ 34",
                quantity: 78 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3.8 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "FEMALE" || "N/A" ,
            },
            {   
                serial: 48,
                name: "Moonracer",
                img: "" ,
                price:  "$ 22",
                quantity: 77 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3.8 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "FEMALE" || "N/A" ,
            },
            {   
                serial: 49,
                name: "Novastar",
                img: "" ,
                price:  "$ 36",
                quantity: 43 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 2.8 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "FEMALE" || "N/A" ,
            },
            {   
                serial: 50,
                name: "Novastar",
                img: "" ,
                price:  "$ 36",
                quantity: 77 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 2.8 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "FEMALE" || "N/A" ,
            },
            {   
                serial: 51,
                name: "Novastar",
                img: "" ,
                price:  "$ 53",
                quantity: 67 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 2.8 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "FEMALE" || "N/A" ,
            },
            {   
                serial: 52,
                name: "Optimus_Prime",
                img: "" ,
                price:  "$ 77",
                quantity: 47 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 4.8 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 53,
                name: "Optimus_Prime",
                img: "" ,
                price:  "$ 88",
                quantity: 45 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 4.8 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 54,
                name: "Optimus_Prime",
                img: "" ,
                price:  "$ 77",
                quantity: 44 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 4.8 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 55,
                name: "Perceptor",
                img: "" ,
                price:  "$ 44",
                quantity: 67 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 4 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 56,
                name: "Perceptor",
                img: "" ,
                price:  "$ 66",
                quantity: 45 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 4 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 57,
                name: "Perceptor",
                img: "" ,
                price:  "$ 64",
                quantity: 34 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 4 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 58,
                name: "Prowl",
                img: "" ,
                price:  "$ 34",
                quantity: 34 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 59,
                name: "Prowl",
                img: "" ,
                price:  "$ 33",
                quantity: 88 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 60,
                name: "Prowl",
                img: "" ,
                price:  "$ 33",
                quantity: 66 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 61,
                name: "Ratchet",
                img: "" ,
                price:  "$ 54",
                quantity: 76 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3.4 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 62,
                name: "Ratchet",
                img: "" ,
                price:  "$ 66",
                quantity: 64 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3.4 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 63,
                name: "Ratchet",
                img: "" ,
                price:  "$ 22",
                quantity: 54 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3.4 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 64,
                name: "Shockwave",
                img: "" ,
                price:  "$ 22",
                quantity: 667 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3.3 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 65,
                name: "Shockwave",
                img: "" ,
                price:  "$ 55",
                quantity: 55 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3.3 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 66,
                name: "Shockwave",
                img: "" ,
                price:  "$ 47",
                quantity: 45 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3.3 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 67,
                name: "Sideswipe",
                img: "" ,
                price:  "$ 34",
                quantity: 37 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" 
            },
            {   
                serial: 68,
                name: "Sideswipe",
                img: "" ,
                price:  "$ 77",
                quantity: 45 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 69,
                name: "Sideswipe",
                img: "" ,
                price:  "$ 45",
                quantity: 45 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 70,
                name: "Soundwave",
                img: "" ,
                price:  "$ 68",
                quantity: 56 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 71,
                name: "Soundwave",
                img: "" ,
                price:  "$ 37",
                quantity:  55,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 72,
                name: "Soundwave",
                img: "" ,
                price:  "$ 74",
                quantity: 35 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 73,
                name: "Starscream",
                img: "" ,
                price:  "$ 73",
                quantity: 35 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 4 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 74,
                name: "Starscream",
                img: "" ,
                price:  "$ 36",
                quantity: 45 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 4 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 75,
                name: "Starscream",
                img: "" ,
                price:  "$ 76",
                quantity: 34 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 4 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 76,
                name: "Ultra_Magnus",
                img: "" ,
                price:  "$ 66",
                quantity: 44 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 4 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "FEMALE" || "N/A" ,
            },
            {   
                serial: 77,
                name: "Ultra_Magnus",
                img: "" ,
                price:  "$ 67",
                quantity: 62 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 4 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "FEMALE" || "N/A" ,
            },
            {   
                serial: 78,
                name: "Ultra_Magnus",
                img: "" ,
                price:  "$ 26",
                quantity: 42 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 4 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "FEMALE" || "N/A" ,
            },
            {   
                serial: 79,
                name: "Wheeljack",
                img: "" ,
                price:  "$ 75",
                quantity: 353 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3.6 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 80,
                name: "Wheeljack",
                img: "" ,
                price:  "$ 65",
                quantity: 53 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3.6 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            },
            {   
                serial: 81,
                name: "Wheeljack",
                img: "" ,
                price:  "$ 73",
                quantity: 35 ,
                description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Et doloremque odit molestias, possimus fugiat eligendi accusamus totam. Fugiat, commodi quod.",
                rating: 3.6 ,
                seller_name: "" || "N/A" ,
                seller_email: "" || "N/A" ,
                sub_category: "MALE" || "N/A" ,
            }
        ]
)
})

app.listen(port, () => {
    console.log('Server is running on :', port);
})
